services:
  shadowsocks_v2ray:
    build: .
    environment:
      PASSWORD: "your password"
    restart: on-failure
  nginx:
    image: nginx:stable
    ports:
      - "0.0.0.0:443:443/tcp"
      - "0.0.0.0:80:80/tcp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/domain.pem:/etc/nginx/certs/domain.pem
      - ./nginx/domain.key:/etc/nginx/certs/domain.key
    restart: on-failure
