services:
  shadowsocks_v2ray:
    build: .
    environment:
      PASSWORD: "your password"
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    ports:
      - 443:443/tcp
      - 80:80/tcp
    environment:
      DOMAIN: "example.com"
      URL_TO_REDIRECT: "https://youtube.com"
      V2RAY_PATH: "/v2ray"
      V2RAY_INTERNAL_URL: "http://shadowsocks_v2ray:8388/"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./domain.pem:/etc/nginx/certs/domain.pem
      - ./domain.key:/etc/nginx/certs/domain.key
    restart: unless-stopped
